postgres:
  image: postgres:latest
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=secret
  ports:
    - 5436:5432
  volumes:
    - ./var/database/database.sql:/docker-entrypoint-initdb.d/database.sql